import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Header } from "@/components/Header";
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  weight: ["400", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();

  const rawLocation = cookieStore.get("@tanamao:location")?.value;
  const savedLocation = rawLocation ? decodeURIComponent(rawLocation) : null;
  const initialLocation = savedLocation || "Descobrir sua região";

  const isUserLoggedIn = cookieStore.has("accessToken") || cookieStore.has("refreshToken");

  const rawUserName = cookieStore.get("userName")?.value;
  const userName = rawUserName ? decodeURIComponent(rawUserName) : null;
  const userRole = cookieStore.get("userRole")?.value ?? null;

  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body className="min-h-screen flex flex-col">
        <Header
          initialLocation={initialLocation}
          isUserLoggedIn={isUserLoggedIn}
          userName={userName}
          userRole={userRole}
        />
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
